version: '2'
services:
    modelbuilder-app:
        image: modelbuilder
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://modelbuilder-mariadb:3306/modelbuilder
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=modelbuilder-elasticsearch:9300
        ports:
            - 8080:8080
    modelbuilder-mariadb:
        extends:
            file: mariadb.yml
            service: modelbuilder-mariadb
    modelbuilder-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: modelbuilder-elasticsearch
